<?php
declare (strict_types = 1);

namespace Hahadu\ImAdminThink\model;


/**
 * @mixin UserBaseModel
 */
class Users extends UserBaseModel
{
    public function addData($data)
    {
        return parent::addData($data); // TODO: Change the autogenerated stub
    }

    public function editData($map, $data)
    {
        return parent::editData($map, $data); // TODO: Change the autogenerated stub
    }

    public function deleteData($map, $type = false)
    {
        return parent::deleteData($map, $type); // TODO: Change the autogenerated stub
    }
}